spring:
  application:
    name: neuromancien
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/test_db}
    database: ${MONGODB_DATABASE:test_db}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    "[org.springframework.data.mongodb]": DEBUG
    "[com.bookbox.neuromancien]": DEBUG
