spring:
  application:
    name: neuromancien
    version: @project.version@
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/test_db}
    database: ${MONGODB_DATABASE:test_db}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    "[org.springframework.data.mongodb]": DEBUG
    "[com.bookbox.neuromancien]": DEBUG

jwt:
  secret: ${JWT_SECRET:default_jwt_secret_key}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

google:
  books:
    api: 
      url: ${GOOGLE_BOOKS_API_URL:https://www.googleapis.com/books/v1}
      key: ${GOOGLE_BOOKS_API_KEY:default_google_books_api_key}
